---
".gitlab-ci.yml":
  delete: true
".yardopts":
  optional:
  - "--output-dir docs/"
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
'.travis.yml':
  global_env: 
    - HONEYCOMB_WRITEKEY="7f3c63a70eecc61d635917de46bea4e6",HONEYCOMB_DATASET="litmus tests"
  deploy_to_forge:
    enabled: false
  branches:
    - release
  user: puppet
  secure: ''
  use_litmus: true
  litmus:
    provision_list:
    - ---travis_el
    - travis_deb
    - travis_el6
    - travis_el7
    complex:
    - collection:
        puppet_collection:
        - puppet6
        provision_list:
        - travis_ub_6
    - collection:
        puppet_collection:
        - puppet5
        provision_list:
        - travis_ub_5
  simplecov: true
  notifications:
    slack:
      secure: XnFGMHjVwgUY0Dtxvent3sa6m7yAF7HH3kRsJ39Oje95cechyfuIIDKX80NBLRS/Zpjm5wCEA6l90hgZMw5H8WmqPyo1LrQGzBsk22abh/XI6y/+N1TKSavgegcf+NnU4w30QO4FNiQCoO8krJHoOPqcIpf/azrPPSWVimMovAE=
